//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POE_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_Favourite
    {
        public int FavouriteID { get; set; }
        public string Username { get; set; }
        public int CityID { get; set; }
    
        public virtual DB_User DB_User { get; set; }
    }
}
