//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POE_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WeatherForecastAppEntities : DbContext
    {
        public WeatherForecastAppEntities()
            : base("name=WeatherForecastAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DB_Favourite> DB_Favourite { get; set; }
        public virtual DbSet<DB_Forecast> DB_Forecast { get; set; }
        public virtual DbSet<DB_User> DB_User { get; set; }
    }
}
